# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Convex Optimization
author: Shailesh Kumar

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/shailesh1729/cvx-opt-book
  path_to_book: book
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

#parse:
#  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    mathjax3_config:
      tex:
        macros:
          "AA": "\\mathbb{A}"
          "BB": "\\mathbb{B}"
          "CC": "\\mathbb{C}"
          "DD": "\\mathbb{D}"
          "EE": "\\mathbb{E}"
          "FF": "\\mathbb{F}"
          "GG": "\\mathbb{G}"
          "HH": "\\mathbb{H}"
          "II": "\\mathbb{I}"
          "JJ": "\\mathbb{J}"
          "KK": "\\mathbb{K}"
          "NN": "\\mathbb{N}"
          "Nat": "\\mathbb{N}"
          "PP": "\\mathbb{P}"
          "QQ": "\\mathbb{Q}"
          "RR": "\\mathbb{R}"
          "RRMN": "\\mathbb{R}^{M \\times N}"
          "TT": "\\mathbb{T}"
          "UU": "\\mathbb{U}"
          # A vector space
          "VV": "\\mathbb{V}"
          # A subspace
          "WW": "\\mathbb{W}"
          # An inner product space
          "XX": "\\mathbb{X}"
          # Integers
          "ZZ": "\\mathbb{Z}"
          # All mathcal shortcuts
          "AAA": "\\mathcal{A}"
          "BBB": "\\mathcal{B}"
          "CCC": "\\mathcal{C}"
          "DDD": "\\mathcal{D}"
          "EEE": "\\mathcal{E}"
          "FFF": "\\mathcal{F}"
          "GGG": "\\mathcal{G}"
          "HHH": "\\mathcal{H}"
          "III": "\\mathcal{I}"
          "JJJ": "\\mathcal{J}"
          "KKK": "\\mathcal{K}"
          "LLL": "\\mathcal{L}"
          "MMM": "\\mathcal{M}"
          "NNN": "\\mathcal{N}"
          "OOO": "\\mathcal{O}"
          "PPP": "\\mathcal{P}"
          "QQQ": "\\mathcal{Q}"
          "RRR": "\\mathcal{R}"
          "SSS": "\\mathcal{S}"
          "TTT": "\\mathcal{T}"
          "UUU": "\\mathcal{U}"
          "VVV": "\\mathcal{V}"
          "WWW": "\\mathcal{W}"
          "XXX": "\\mathcal{X}"
          "YYY": "\\mathcal{Y}"
          "ZZZ": "\\mathcal{Z}"
          "Tau": "\\mathcal{T}"
          "Chi": "\\mathcal{X}"
          "Eta": "\\mathcal{H}"
          # Real part of a complex number
          "Re": "\\operatorname{Re}"
          "Im": "\\operatorname{Im}"
          # Null space
          "NullSpace": "\\mathcal{N}"
          # Column space
          "ColSpace": "\\mathcal{C}"
          # Row space
          "RowSpace": "\\mathcal{R}"
          # Power set
          "Power": "\\mathop{\\mathcal{P}}"
          "LinTSpace": "\\mathcal{L}"
          # Range
          "Range": "\\mathrm{R}"
          # image
          "Image": "\\mathrm{im}"
          # Kernel
          "Kernel": "\\mathrm{ker}"
          # Span
          "Span": "\\mathrm{span}"
          # Nullity of an operator
          "Nullity": "\\mathrm{nullity}"
          # Dimension of a vector space
          "Dim": "\\mathrm{dim}"
          # Rank of a matrix
          "Rank": "\\mathrm{rank}"
          # Trace of a matrix
          "Trace": "\\mathrm{tr}"
          # Diagonal of a matrix
          "Diag": "\\mathrm{diag}"
          # Signum function
          "sgn": "\\mathrm{sgn}"
          # Support function
          "supp": "\\mathrm{supp}"
          # Row support
          "rowsupp": "\\mathop{\\mathrm{rowsupp}}"
          # Entry wise absolute value function
          "abs": "\\mathop{\\mathrm{abs}}"
          # error function
          "erf": "\\mathop{\\mathrm{erf}}"
          # complementary error function
          "erfc": "\\mathop{\\mathrm{erfc}}"
          # Sub Gaussian function
          "Sub": "\\mathop{\\mathrm{Sub}}"
          # Strictly sub Gaussian function
          "SSub": "\\mathop{\\mathrm{SSub}}"
          # Variance function
          "Var": "\\mathop{\\mathrm{Var}}"
          # Covariance matrix
          "Cov": "\\mathop{\\mathrm{Cov}}"
          # Affine hull of a set
          "AffineHull": "\\mathop{\\mathrm{aff}}"
          # Convex hull of a set
          "ConvexHull": "\\mathop{\\mathrm{conv}}"
          # Set theory related stuff
          "argmin": "\\mathrm{arg}\\,\\mathrm{min}"
          "argmax": "\\mathrm{arg}\\,\\mathrm{max}"
          "EmptySet": "\\varnothing"
          # Forall operator with some space
          "Forall": "\\; \\forall \\;"
          # Probability distributions
          "Gaussian": "\\mathcal{N}"
          # Sparse representations related stuff
          # Spark of a matrix
          "spark": "\\mathop{\\mathrm{spark}}"
          # Exact Recovery Criterion
          "ERC": "\\mathop{\\mathrm{ERC}}"
          # Maximum correlation
          "Maxcor": "\\mathop{\\mathrm{maxcor}}"
          # pseudo-inverse
          "dag": "\\dagger"
          # bracket operator
          "Bracket": "\\left [ \\; \\right ]"
          # OneVec
          "OneVec": "\\mathbb{1}"
          "ZeroVec": "0"
          "OneMat": "\\mathbf{1}"
          # Topology related stuff
          "Interior": ["\\mathring{#1}", 1]
          "Closure": ["\\overline{#1}", 1]


